server.port=8080

spring.profiles.active=secret

spring.datasource.url=jdbc:mysql://localhost:3306/mini-project-task-manager
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

logging.level.root=INFO

jwt.secret=1234567890qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890

jwt.expiration=360000

jwt.clock-skew-seconds=60

cors.allowed-origins=*
cors.allowed-headers=*
cors.allowed-method=GET,POST,PUT,PATCH,DELETE,OPTIONS
cors.exposed-headers=Authorization,Set-cookie

security.h2-console=true
